### ISSUE TITLE
Name inconsistency between character voices and portraits folders

### ISSUE THREAD

**Issue by Xwilarg** [vg-mjg/majsoul-plus-mods#2]
Hey,

So I wrote a small script to parse the data from https://files.riichi.moe/mjg/game%20resources%20and%20tools/Mahjong%20Soul/game%20files/ and I noticed that some character names are differents between the character voices and portraits folders:

Ako Aratashi > Ako Atarashi
Chiori Mikami > Chiori
Kana Fujita > Fujita Kana
Mai Aihara > Aihara Mai
Miki Nikaidou > Nikaido Miki
Riu Kujou > Kujou Riu
Yui Yagi > Yagi Yui

**Comment by watterle** [comment]
I think he's using his own script to parse from majsoul (https://github.com/chinponya/asset_janny) so open an issue there.
